name: 'Adevinta Vulcan Action'
description: 'Scans your repository for vulnerabilities vulcan'
author: 'Adevinta'
inputs:
  config:
    description: 'Path or uri (file:// http://) to a vulcan config yaml'
    required: false
    default: ''
  checkTypes:
    description: 'Path or uri to a checktypes definition'
    required: false
    default: ''
  include:
    description: 'Regex of checks to include (eg. trivy)'
    required: false
    default: ''
  exclude:
    description: 'Regex of checs to exclude (eg. zap)'
    required: false
    default: ''
  policy:
    description: 'Policy to use'
    required: false
    default: ''
  target:
    description: 'Target to scan (eg ., http://localhost:1234'
    required: false
    default: ''
  assetType:
    description: 'Asset type of the target (eg. DockerImage, GitRepository, WebAddress, ...)'
    required: false
    default: ''
  severity:
    description: 'Severity (eg. error info debug)'
    required: false
    default: ''
  logLevel:
    description: 'Log level (eg. CR)'
    required: false
    default: ''
runs:
  using: 'docker'
  image: "Dockerfile"
